export const data = {
  BTech: {
    1: [
      "Engineering Physics",
      "Engineering chem",
      "Engineering maths",
      "programming for problem solving",
      "Programming with python",
    ],
    2: [
      "Engineering Physics",
      "Engineering maths",
      "programming for problem solving",
      "Programming with python",
    ],
    3: ["Engineering Physics"],
    4: ["Engineering Physics"],
    5: ["Engineering Physics"],
    6: ["Engineering Physics"],
    7: ["Engineering Physics"],
    8: ["Engineering Physics"],
  },
  BCA: {
    1: [
      "Engineering Physics",
      "Engineering chem",
      "Engineering maths",
      "programming for problem solving",
      "Programming with python",
    ],
    2: [
      "Engineering Physics",
      "Engineering maths",
      "programming for problem solving",
      "Programming with python",
    ],
    3: ["Engineering Physics"],
    4: ["Engineering Physics"],
    5: ["Engineering Physics"],
    6: ["Engineering Physics"],
    7: ["Engineering Physics"],
    8: ["Engineering Physics"],
  },
  LAW: {
    1: [
      "Engineering Physics",
      "Engineering chem",
      "Engineering maths",
      "programming for problem solving",
      "Programming with python",
    ],
    2: [
      "Engineering Physics",
      "Engineering maths",
      "programming for problem solving",
      "Programming with python",
    ],
    3: ["Engineering Physics"],
    4: ["Engineering Physics"],
    5: ["Engineering Physics"],
    6: ["Engineering Physics"],
    7: ["Engineering Physics"],
    8: ["Engineering Physics"],
  },
};
