export const data = {
  BTech: {
    1: [
      "THU101 - Professional Communication",
      "TPH101 - Engineering Physics",
      "TMA101 - Engineering Mathematics-I",
      "TEE101 - Basic Electrical Engineering",
      "TCS101 - Fundamental of Computer & Introduction to Programming",
      "THF101 - Healthy Living & Fitness",
      "PPH151 - Physics Lab",
      "PEE151 - Basic Electrical Engineering Lab.",
      "PME151 - Workshop and Manufacturing Practices",
      "PCS151 - Computer Lab-I",
      "GP101 - General Proficiency",
      "TCH101 - Engineering Chemistry",
      "TEC101 - Basic Electronics Engineering",
      "TEV101 - Environmental Science",
      "PCH151 - Chemistry Lab",
      "PME153 - Engg. Graphics and Design Lab.",
      "PEC151 - Basic Electronics Engineering Lab.",
    ],
    2: [
      "THU201 - Advanced Professional Communication",
      "TPH201 - Engineering Physics",
      "TMA201 - Engineering Mathematics-II",
      "TEE201 - Basic Electrical Engineering",
      "TCS201 - Programming for Problem Solving",
      "THF201 - Healthy Living & Fitness",
      "PPH251 - Physics Lab",
      "PEE201 - Basic Electrical Engineering Lab.",
      "PME251 - Workshop and Manufacturing Practices",
      "PCS251 - Computer Lab-II",
      "GP201 - General Proficiency",
      "TCH201 - Engineering Chemistry",
      "TEC201 - Basic Electronics Engineering",
      "TEV201 - Environmental Science",
      "PCH251 - Chemistry Lab",
      "PME253 - Engg. Graphics and Design Lab.",
      "PEC251 - Basic Electronics",
    ],
    3: [
      "TCS-301 - Logic Design",
      "TCS-302 - Data Structures with C",
      "TCS-307 - Object Oriented Programming with C++",
      "TMA-316 - Discrete Structures and Combinatorics",
      "PCS-301 - Logic Design Lab",
      "PCS-302 - Data Structures Lab",
      "PCS-307 - OOPS with C++ Lab",
      "XCS-301 - Career Skills",
      "CSP-301 - Mini Project",
      "GP-301 - General Proficiency",
      "TCS-351 - Fundamental of Cloud Computing and Bigdata",
      "TCS-391 - Fundamental of Cyber Security",
      "TCS-331 - Fundamental of IoT",
      "TCS-320 - Application Based Programming in Python (Through Swayam)",
      "TOC301 - Probability and Statistics",
    ],
    4: [" "],
    5: [" "],
    6: [" "],
    7: [" "],
    8: [
      "TDM-881 - Disaster Management",
      "TCS-851 - Storage Networks",
      "TCS-802 - Mobile Computing",
    ],
  },
  BCA: {
    1: [
      "Engineering Physics",
      "Engineering chem",
      "Engineering maths",
      "programming for problem solving",
      "Programming with python",
    ],
    2: [
      "Engineering Physics",
      "Engineering maths",
      "programming for problem solving",
      "Programming with python",
    ],
    3: ["Engineering Physics"],
    4: ["Engineering Physics"],
    5: ["Engineering Physics"],
    6: ["Engineering Physics"],
    7: ["Engineering Physics"],
    8: ["Engineering Physics"],
  },
  LAW: {
    1: [
      "Engineering Physics",
      "Engineering chem",
      "Engineering maths",
      "programming for problem solving",
      "Programming with python",
    ],
    2: [
      "Engineering Physics",
      "Engineering maths",
      "programming for problem solving",
      "Programming with python",
    ],
    3: ["Engineering Physics"],
    4: ["Engineering Physics"],
    5: ["Engineering Physics"],
    6: ["Engineering Physics"],
    7: ["Engineering Physics"],
    8: ["Engineering Physics"],
  },
};
